# Generated by Django 2.1.15 on 2019-12-22 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('back_number', models.IntegerField()),
                ('position', models.CharField(choices=[('1', 'ピッチャー'), ('2', 'キャッチャー'), ('3', 'ファースト'), ('4', 'セカンド'), ('5', 'サード'), ('6', 'ショート'), ('7', 'レフト'), ('8', 'センター'), ('9', 'ライト')], max_length=1)),
                ('sub_position', models.CharField(choices=[('1', 'ピッチャー'), ('2', 'キャッチャー'), ('3', 'ファースト'), ('4', 'セカンド'), ('5', 'サード'), ('6', 'ショート'), ('7', 'レフト'), ('8', 'センター'), ('9', 'ライト')], max_length=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
