# Generated by Django 2.1.15 on 2020-01-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200104_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='back_number',
            field=models.IntegerField(default=0),
        ),
    ]
